### ISSUE TITLE
keyplus-cli passthrough issues with wireless dongle

### ISSUE THREAD

**Issue by Merlin04** [ahtn/keyplus#55]
```fish
sudo python3 keyplus-cli passthrough
Traceback (most recent call last):
  File "keyplus-cli", line 792, in <module>
    KeyplusCLI()
  File "keyplus-cli", line 782, in __init__
    command_list[args.command].run()
  File "keyplus-cli", line 105, in run
    self.task(args)
  File "keyplus-cli", line 217, in task
    kp_layout = kb.unpack_layout_data()
  File "/home/me/keyplus/git/keyplus/host-software/keyplus/keyboard.py", line 574, in unpack_layout_data
    layout_arrays = self._get_layout_keycode_arrays(layout_data)
  File "/home/me/keyplus/git/keyplus/host-software/keyplus/keyboard.py", line 528, in _get_layout_keycode_arrays
    devices = self.layout_settings.get_layout_device_sizes(layout_i)
  File "/home/me/keyplus/git/keyplus/host-software/keyplus/device_info.py", line 213, in get_layout_device_sizes
    "Unexpected overlap in matrix_sizes: {}".format(devices)
keyplus.exceptions.KeyplusSettingsError: Unexpected overlap in matrix_sizes: [device_info_t(layout_id=0, matrix_offset=0, matrix_size=5), device_info_t(layout_id=0, matrix_offset=7, matrix_size=7)]
```

Not sure what's happening, could it be that my right half of the keyboard is larger than the left half?

**Comment by ahtn** [comment]
The passthrough mode only works on devices connected via USB.  This is because, the devices map there key presses from a (row, col) number to a single key number before transmitting to the receiver. So the receiver, doesn't know what (row, col) number was sent.

`keyplus-cli` should be changed show an error if you attempt to use it on a device with `no_matrix`. Also, it this limitation should be documented.
